name: wp
services:
  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile.NGINX
    volumes:
      - data:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    image: wordpress:fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    volumes:
      - data:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: define('WP_MEMORY_LIMIT', '3000M');
    restart: unless-stopped

  mariadb:
    restart: unless-stopped
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      #- MYSQL_ROOT_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8080

volumes:
  db-data:
  data: